[package]
name = "glow-web"
version = "0.1.0"
authors = ["Rob Young <rob@robyoung.digital>"]
edition = "2018"

[dependencies]
actix-web = "2.0"
actix-web-httpauth = "0.4.0"
actix-rt = "1.0"

r2d2 = "0.8"
r2d2_sqlite = "0.14"
rusqlite = "0.21"

chrono = { version = "0.4", features = ["serde"] }
env_logger = "0.6"
serde_json = "1.0"

glow_events = { path = "../glow_events" }
