[package]
name = "glow_events"
version = "0.1.0"
authors = ["Rob Young <rob@robyoung.digital>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
am2320 = "0.2.0"

[dev-dependencies]
serde_json = "1.0"
